---
title: "AI Analytics 2 - Data Comparison"
author: Alex
date: '2018-02-21'
slug: ai-analytic-02
categories:
  - AI
  - R
tags:
  - AI
  - analysis
  - machine learning
  - plot
  - R
  - R Markdown
  - regression
  - visualization
---

Read in data and functions
```{r}
library(knitr)
library(kableExtra)
source("2018-02-21-ai-analytics/BDVis.R")
source("2018-02-21-ai-analytics/UniVarAnal.R")
CH1.demo<-readRDS("2018-02-21-ai-analytics/CH1.demo.RDS")
CH1.out<-readRDS("2018-02-21-ai-analytics/CH1.out.RDS")
pat.grp<-CH1.out[,1:2]
pat.grp$Death<-sapply(as.character(pat.grp$Death),function(x)switch(x,"0"="Alive","1"="Death"))
names(pat.grp)[2]<-"group"
CH1.demo<-left_join(CH1.demo,pat.grp)
```


Visualization code
```{r}
#Age distribution
vis.age<-age.vis(CH1.demo[,getcolumn("age|group",CH1.demo)])
tab.age<-coef.temp.func(CH1.demo,"age|group")

#Gender distribution
cat.df<-col.aggr("gender|group",CH1.demo)
vis.gender<-cat.vis(cat.df,Title="Gender")
tab.gender<-coef.temp.func(CH1.demo,"gender|group")


#Race distribution
cat.df<-col.aggr("Race|group",CH1.demo)
vis.race<-cat.vis(cat.df,Title="Ethnicity")
tab.race<-coef.temp.func(CH1.demo,"race|group")


#Marital status distribution
cat.df<-col.aggr("marital|group",CH1.demo)
cat.df[c(1,6),1]<-"Devorced"
vis.marital<-cat.vis(cat.df,Title="Marital Status")
tab.marital<-coef.temp.func(CH1.demo,"marital|group")


#Medifund distribution
cat.df<-col.aggr("mediFundHx|group",CH1.demo)
cat.df[,1]<-rep(c("No","Yes"),2)
vis.medifund<-cat.vis(cat.df,Title="MediFund")
tab.mediFundHx<-coef.temp.func(CH1.demo,"mediFundHx|group")



#Diabetes year distribution
cat.df<-col.aggr("Diabetes_year|group",CH1.demo)
cat.df$Diabetes_year<-factor(cat.df$Diabetes_year,levels=cat.df[c(1,3:5,2),1])
vis.diab.yr<-cat.vis(cat.df,Title="Diabetes Year")
tab.diab.yr<-coef.temp.func(CH1.demo,"Diabetes_year|group")


#Patient type distribution
cat.df<-col.aggr("PAT_TYPE|group",CH1.demo)
vis.pat_type<-cat.vis(cat.df,Title="Patient type")
tab.pat_type<-coef.temp.func(CH1.demo,"PAT_TYPE|group")



#Disease Prevalence
demo.sub<-CH1.demo[,c(8:19,22)]
names(demo.sub)[c(7,11,12)]<-c("Heart Failure","Major Amputation","Minor Amputation")
prev.df<-cols.aggr(demo.sub)
prev.df<-df.sort(prev.df)
vis.prev<-Prev.vis(prev.df)
```
## Individual Visualization

Age distribution

```{r,echo = FALSE, results = 'asis'}
vis.age
tab.age
```

Gender distribution
```{r,echo = FALSE}
vis.gender
tab.gender
```

Race distribution
```{r,echo = FALSE}
vis.race
tab.race
```

Marital status distribution
```{r,echo = FALSE}
vis.marital
tab.marital
```

Medifund distribution
```{r,echo = FALSE}
vis.medifund
tab.marital
```


Diabetes year distribution
```{r,echo = FALSE}
vis.diab.yr
tab.diab.yr
```

Patient type distribution
```{r,echo = FALSE}
vis.pat_type
tab.pat_type
```

Disease Prevalence
```{r,echo = FALSE}
vis.prev
```

## Dashboard
### Demographic
```{r,fig.asp = 1.2,fig.width=10}
grid.arrange(vis.age,vis.gender,vis.race,vis.marital,layout_matrix=matrix(1:4,2,2,byrow=T))
```


Disease related history
```{r,fig.asp = 1.2,fig.width=10}
grid.arrange(vis.diab.yr,vis.medifund,vis.pat_type,layout_matrix=matrix(c(1,1,2,3),2,2,byrow=T))
```


Disease prevalence
```{r,echo = FALSE}
vis.prev
```