---
title: "AI Analytics 3 - Risk Prediction"
author: Alex
date: '2018-02-26'
slug: ai-analytic-03
categories:
  - AI
  - R
tags:
  - AI
  - analysis
  - machine learning
  - plot
  - R
  - regression
  - R Markdown
  - visualization
---

Read in data and functions
```{r}
library(knitr)
library(kableExtra)
source("2018-02-21-ai-analytics/BDVis.R")
source("2018-02-21-ai-analytics/UniVarAnal.R")
source("2018-02-21-ai-analytics/RiskPrediction.R")
demo.proc<-readRDS("2018-02-21-ai-analytics/demo.proc.RDS")
demo.proc$AGE<-as.integer(as.character(demo.proc$AGE))
demo.proc$GENDER<-factor(demo.proc$GENDER,levels=c("Female","Male"))
demo.proc$RACE<-factor(demo.proc$RACE,levels=c("Others","Chinese","Malay","Indian"))


mdl.data<-demo.proc[,c(1,3:8,21,9:20,22,26:27,29,23:25)]


# model structure: 1.variable rename, 2. variable grouping
mdl.strct<-data.frame(
  Variable=names(mdl.data),
  rename=c("Death","Age","Gender","Race","Marital","MediFund","DiabetesYear","PatType",names(mdl.data)[9:18],"MajorAmputation","MinorAmputation","BMI",names(mdl.data)[22:27]),
  VarGrp=c("Outcome",rep("Demographics",4),rep("Medical History",3),rep("Comorbidity & Complication",12),rep("Physiological Measure",4),rep("Score",3)),
  stringsAsFactors=F
)

mdl.strct<-cbind(mdl.strct,getClassRef(mdl.data))

names(mdl.data)<-mdl.strct$rename

names(mdl.data)<-mdl.strct$rename
mdl.glm<-log.reg(mdl.data)
coef.proc.df<-coef.proc(summary(mdl.glm)$coef)
coef.proc.df<-coef.intpt(coef.proc.df,mdl.data,mdl.strct)
```




```{r}
coef.df.to.kable(coef.proc.df)
```







